version: "3.8"
networks:
  default:
    ipam:
      config:
        - subnet: 172.99.0.0/16
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    hostname: zookeeper
    ports:
      - '2181'
    restart: always
    environment:
      - ZOO_TICK_TIME=2000
      - ALLOW_ANONYMOUS_LOGIN=yes

  zookeeper-setup:
    image: zookeeper:3.6.2
    command: /faas/tmp/zk_setup.sh
    depends_on:
       - zookeeper
    volumes:
      - ${FAAS_DIR:?}:/faas
    restart: always

  faas-engine:
    image: ubuntu:focal
    hostname: faas-engine-{{.Task.Slot}}
    entrypoint:
      - /faas/bin/${FAAS_BUILD_TYPE:-release}/engine
      - --zookeeper_host=zookeeper:2181
      - --listen_iface=eth0
      - --root_path_for_ipc=/tmp/faas/ipc
      - --func_config_file=/exp/lat_tp/specs/produce_consume.json
      - --num_io_workers=4
      - --socket_listen_backlog=1024
      - --instant_rps_p_norm=0.8
      - --io_uring_entries=2048
      - --io_uring_fd_slots=4096
      - --enable_shared_log
      - --slog_engine_enable_cache
      - --slog_engine_cache_cap_mb=1024
      - --slog_engine_propagate_auxdata
    depends_on:
      - zookeeper-setup
    volumes:
      - ${FAAS_DIR:?}:/faas
      - ${EXP_DIR:?}:/exp
      - /mnt/inmem/faas:/tmp/faas
      - /mnt/inmem/log:/tmp/log
      - /sys/fs/cgroup:/tmp/root_cgroupfs
    environment:
      - FAAS_NODE_ID={{.Task.Slot}}
      - FAAS_CGROUP_FS_ROOT=/tmp/root_cgroupfs
    restart: always

  faas-controller:
    image: ubuntu:focal
    entrypoint:
      - /faas/bin/${FAAS_BUILD_TYPE:-release}/controller
      - --zookeeper_host=zookeeper:2181
      - --metalog_replicas=3
      - --userlog_replicas=3
      - --index_replicas=2
    depends_on:
      - zookeeper-setup
    volumes:
      - ${FAAS_DIR:?}:/faas
    restart: always

  faas-gateway:
    image: ubuntu:focal
    hostname: faas-gateway
    ports:
      - 8080:8080
    entrypoint:
      - /faas/bin/${FAAS_BUILD_TYPE:-release}/gateway
      - --zookeeper_host=zookeeper:2181
      - --listen_iface=eth0
      - --http_port=8080
      - --func_config_file=/exp/lat_tp/specs/produce_consume.json
      - --num_io_workers=8
      - --socket_listen_backlog=1024
      - --io_uring_entries=2048
      - --io_uring_fd_slots=4096
      - --lb_per_fn_round_robin
      - --max_running_requests=0
    depends_on:
      - zookeeper-setup
    volumes:
      - ${EXP_DIR:?}:/exp
      - ${FAAS_DIR:?}:/faas
      - /mnt/inmem:/tmp
    restart: always

  faas-storage:
    image: ubuntu:focal
    hostname: faas-storage-{{.Task.Slot}}
    entrypoint:
      - /faas/bin/${FAAS_BUILD_TYPE:-release}/storage
      - --zookeeper_host=zookeeper:2181
      - --listen_iface=eth0
      - --db_path=/tmp/storage/logdata
      - --num_io_workers=4
      - --socket_listen_backlog=1024
      - --io_uring_entries=2048
      - --io_uring_fd_slots=4096
      - --slog_local_cut_interval_us=500
      - --slog_storage_backend=rocksdb
      - --slog_storage_cache_cap_mb=2048
      - --rocksdb_max_background_jobs=2
    depends_on:
      - zookeeper-setup
    volumes:
      - ${FAAS_DIR:?}:/faas
      - /mnt/storage:/tmp/storage
      - /mnt/inmem/log:/tmp/log
    environment:
      - FAAS_NODE_ID={{.Task.Slot}}
    restart: always

  faas-sequencer:
    image: ubuntu:focal
    hostname: faas-sequencer-{{.Task.Slot}}
    entrypoint:
      - /faas/bin/${FAAS_BUILD_TYPE:-release}/sequencer
      - --zookeeper_host=zookeeper:2181
      - --listen_iface=eth0
      - --num_io_workers=4
      - --socket_listen_backlog=1024
      - --io_uring_entries=2048
      - --io_uring_fd_slots=4096
      - --slog_global_cut_interval_us=500
    depends_on:
      - zookeeper-setup
    volumes:
      - ${FAAS_DIR:?}:/faas
      - /mnt/storage:/tmp/storage
      - /mnt/inmem/log:/tmp/log
    environment:
      - FAAS_NODE_ID={{.Task.Slot}}
    restart: always

  scale:
    image: ubuntu:focal
    entrypoint: ["/faas/tmp/run_basic_go", "/src/bin/lat_tp_handler", "40"]
    volumes:
      - ${SRC_DIR:?}:/src
      - ${FAAS_DIR:?}:/faas
      - /mnt/inmem/faas:/tmp/faas
    environment:
       - FAAS_BUILD_TYPE=${FAAS_BUILD_TYPE:-release}
       - FAAS_GO_MAX_PROC_FACTOR=1
       - GOGC=200
    depends_on:
       - faas-engine
    restart: always

  produce:
    image: ubuntu:focal
    entrypoint: ["/faas/tmp/run_basic_go", "/src/bin/lat_tp_handler", "20"]
    volumes:
      - ${SRC_DIR:?}:/src
      - ${FAAS_DIR:?}:/faas
      - /mnt/inmem/faas:/tmp/faas
    environment:
       - FAAS_BUILD_TYPE=${FAAS_BUILD_TYPE:-release}
       - FAAS_GO_MAX_PROC_FACTOR=1
       - GOGC=200
    depends_on:
       - faas-engine
    restart: always

  consume:
    image: ubuntu:focal
    entrypoint: ["/faas/tmp/run_basic_go", "/src/bin/lat_tp_handler", "30"]
    volumes:
      - ${SRC_DIR:?}:/src
      - ${FAAS_DIR:?}:/faas
      - /mnt/inmem/faas:/tmp/faas
    environment:
       - FAAS_BUILD_TYPE=${FAAS_BUILD_TYPE:-release}
       - FAAS_GO_MAX_PROC_FACTOR=1
       - GOGC=200
    depends_on:
       - faas-engine
    restart: always
